"""
Django settings for MyFirstDjango project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

""" 项目的基础目录路径。 """
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
""" 用于提供加密签名的密钥，应保持秘密 """
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@x+um0g+qqj2d+fp8v3dvw@9y&+a&!s+uh1&$n&=23f0j3h@i%'

""" 是否启用调试模式（仅在开发环境下使用） """
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
""" 允许访问该 Django 应用的主机/域名列表 """
ALLOWED_HOSTS = []


# Application definition
""" INSTALLED_APPS: Django 项目中启用的应用程序列表，包括 Django 自带的和自定义的应用。 """
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'TestModel',               # 添加此项
]
""" MIDDLEWARE: 项目中使用的中间件组件列表，用于处理请求和响应的各种处理逻辑。 """
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
""" ROOT_URLCONF: 项目根 URL 配置模块。 """
ROOT_URLCONF = 'MyFirstDjango.urls'
""" TEMPLATES: 模板引擎配置，包括模板目录和上下文处理器。 """
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 这里需要注意真实的路径templates模板路径在base_dir下面，和命令行文件manage.py同一个目录
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
""" wsgi应用 """
WSGI_APPLICATION = 'MyFirstDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
""" 数据库 本项目用的sqlite3 """
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default':
    {
        'ENGINE': 'django.db.backends.mysql',    # 数据库引擎
        'NAME': 'demo', # 数据库名称
        'HOST': '127.0.0.1', # 数据库地址，本机 ip 地址 127.0.0.1
        'PORT': 3306, # 端口
        'USER': 'root',  # 数据库用户名
        'PASSWORD': 'root', # 数据库密码
    },
    'sqlite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
""" 密码验证器，这里定义了多个验证器 密码相似，密码最小长度，常用密码，数字化 """
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

""" 国际化设置 """
# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

""" 静态文件路由 """
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
""" 默认主键类型：使用 64 位整数（bigint）作为自动递增的主键 """
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
